import argparse
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from src.experiments.freeze import _edgar_company, _gdelt_fetch_month
from src.experiments.news_store import NewsStore, months_for_window
from src.util.log_config import setup_logging

logger = setup_logging("prefetch_news")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Download point-in-time news into the local archive."
    )

    parser.add_argument(
        "--cells",
        default=None,
        help="File of 'TICKER YYYY-MM' cells generated by plan_news_cells.py.",
    )
    parser.add_argument(
        "--ticker-pool",
        default=None,
        help="Newline-separated ticker file or a single ticker.",
    )
    parser.add_argument(
        "--start", default=None, help="First date to cover (YYYY-MM-DD)."
    )
    parser.add_argument("--end", default=None, help="Last date to cover (YYYY-MM-DD).")
    parser.add_argument("--store", default=None, help="SQLite archive path.")
    parser.add_argument(
        "--max-sweeps",
        type=int,
        default=0,
        help="Maximum retry sweeps; zero retries while progress is made.",
    )
    args = parser.parse_args(argv)
    if args.cells is None and not (args.ticker_pool and args.start and args.end):
        parser.error("provide --cells, or --ticker-pool with --start and --end")

    return args


def load_tickers(spec):
    path = Path(spec)
    if path.exists():
        return [
            line.strip()
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
    return [spec.strip()]


def load_cells(path):
    plan = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line or line.startswith("#"):
            continue
        ticker, month = line.split()
        plan.setdefault(ticker, []).append(month)
    for months in plan.values():
        months.sort()
    return plan


def _sweep(store, plan, total):
    failures = []
    done = 0
    names = {}
    for ticker, months in plan.items():
        pending = [month for month in months if not store.has_month(ticker, month)]
        if not pending:
            done += len(months)
            continue

        if ticker not in names:
            company = _edgar_company(ticker)
            names[ticker] = getattr(company, "name", None) or ticker
        for month in months:
            if store.has_month(ticker, month):
                done += 1

                continue

            try:
                store.ensure_window(
                    ticker,
                    f"{month}-01",
                    f"{month}-28",
                    fetch_month=lambda m, name=names[ticker]: _gdelt_fetch_month(
                        name, m
                    ),
                )
            except Exception as exc:
                failures.append(f"{ticker} {month}")
                logger.warning("Failed %s %s: %s", ticker, month, exc)
            done += 1
            if done % 25 == 0:
                logger.info("Progress: %d/%d cells", done, total)
    return failures


def main(argv=None):
    args = parse_args(argv)
    store = NewsStore(args.store)

    if args.cells:
        plan = load_cells(args.cells)
    else:
        months = months_for_window(args.start, args.end)

        plan = {ticker: months for ticker in load_tickers(args.ticker_pool)}

    total = sum(len(months) for months in plan.values())

    logger.info(
        "Covering %d cells across %d tickers -> %s", total, len(plan), store.path
    )

    sweep_no = 0
    previous_failures = None
    while True:
        sweep_no += 1
        failures = _sweep(store, plan, total)

        if not failures:
            logger.info("Archive complete: %d cells covered", total)
            return
        logger.warning(
            "Sweep %d: %d cells still missing: %s%s",
            sweep_no,
            len(failures),
            failures[:15],
            " ..." if len(failures) > 15 else "",
        )

        if args.max_sweeps and sweep_no >= args.max_sweeps:
            logger.warning("Giving up after %d sweeps (re-run to resume).", sweep_no)

            sys.exit(1)
        if previous_failures is not None and failures == previous_failures:
            logger.warning(
                "No progress in the last sweep - GDELT appears blocked. "
                "Re-run later to resume; already-fetched months stay cached."
            )
            sys.exit(1)
        previous_failures = failures
        logger.info("Cooling down 300s before sweep %d ...", sweep_no + 1)
        time.sleep(300)


if __name__ == "__main__":
    main(sys.argv[1:])
