import tracemalloc
import tracemalloc
from dotenv import load_dotenv
from src.util.log_config import setup_logging
from src.agents import fundamental_agent_node
from src.types import ConversationState
from src.infrastructure.mcp import shutdown_mcp
from src.infrastructure.tools import create_tenk_filing_repl, create_tenq_filing_repl
logger = setup_logging('main')

def main(): 
    load_dotenv()
    tracemalloc.start()
    try:
        test_state: ConversationState = {
            'messages': [],
            'next_agent': 'fundamental_agent',
            'ticker': 'AAPL',
            'company_data': '',
            'fundamental_analysis': '',
            'technical_analysis': '',
            'discussion_round': 0,
            'final_recommendation': '',
            'documentation_results': None,
            'search_results': None,
            'prompt': 'Placeholder'
        }
        create_tenk_filing_repl(test_state['ticker'])
        create_tenq_filing_repl(test_state['ticker'])
        res = fundamental_agent_node(test_state)
        assert res['messages'] != [], print('No message generated by agent')
        assert res['fundamental_analysis'] != '', print('No fundamental analysis in the returned state')    
        assert res['next_agent'] == 'technical_agent', print('Failed to set the next agent')
        print("=== Agent Output ===")
        print(res['fundamental_analysis'])
        print(f"\nDiscussion round: {res['discussion_round']}")
    
    finally:
        shutdown_mcp()
    
if __name__ == '__main__': 
    main()