import tracemalloc
from dotenv import load_dotenv
from src.util.log_config import setup_logging
from src.agents import sentiment_agent_node
from src.types import ConversationState
from src.infrastructure.mcp import shutdown_mcp
from src.infrastructure.tools import retrieve_yahoo_data
logger = setup_logging('main')

def main(): 
    load_dotenv()
    tracemalloc.start()
    try:
        test_state: ConversationState = {
            'messages': [],
            'next_agent': 'sentiment_agent',
            'ticker': 'AAPL',
            'company_data': '',
            'fundamental_analysis': '',
            'valuation_analysis': '',
            'sentiment_analysis': '',
            'discussion_round': 1,
            'final_recommendation': '',
            'documentation_results': None,
            'search_results': None,
            'prompt': 'Placeholder'
        }

        res = sentiment_agent_node(test_state)
        assert res['messages'] != [], print('No message generated by agent')
        assert res['sentiment_analysis'] != '', print('No fundamental analysis in the returned state')    
        print("=== Agent Output ===")
        print(res['sentiment_analysis'])
        print(f"\nDiscussion round: {res['discussion_round']}")

    finally:
        shutdown_mcp()
    
        

if __name__ == '__main__': 
    main()