from src.agents import fundamental_agent_node
from src.types import ConversationState

def test_fundamental_agent(): 
    test_state: ConversationState = {
        'messages': [],
        'next_agent': 'fundamental_agent',
        'ticker': 'AAPL',
        'company_data': '',
        'fundamental_analysis': '',
        'technical_analysis': '',
        'discussion_round': 0,
        'final_recommendation': '',
        'documentation_results': None,
        'search_results': None,
        'prompt': 'Placeholder'
    }
    res = fundamental_agent_node(test_state)
    assert res['messages'] != [], print('No message generated by agent')
    assert res['fundamental_analysis'] != '', print('No fundamental analysis in the returned state')    
    assert res['next_agent'] == 'technical_agent', print('Failed to set the next agent')
    print("=== Agent Output ===")
    print(res['fundamental_analysis'])
    print(f"\nDiscussion round: {res['discussion_round']}")
    
